{
    'name': 'ESG Reporting and Analytics',
    'version': '1.1',
    'category': 'Reporting',
    'summary': 'ESG Reporting and Analytics with self-contained asset management',
    'description': 'This module provides a standalone solution for ESG reporting, including its own asset management system.',
    'author': 'Your Company',
    'website': 'https://www.yourcompany.com',
    'depends': [
        'base',
        'mail',
        'web',
        'purchase',
        'facilities_management',
    ],
    'data': [
        'security/ir.model.access.csv',
        'views/esg_asset_views.xml',
        'views/esg_asset_menus.xml',
        'views/enhanced_esg_wizard_views.xml',
        'report/esg_reports.xml',
        'report/esg_report_templates.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
    'license': 'LGPL-3',
}